# permissions for end users to edit clusterissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterissuer-editor-role
rules:
  - apiGroups:
      - cert-manager.heers.it
    resources:
      - clusterissuers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cert-manager.heers.it
    resources:
      - clusterissuers/status
    verbs:
      - get
