# permissions for end users to view scepclusterissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterissuer-viewer-role
rules:
  - apiGroups:
      - cert-manager.heers.it
    resources:
      - scepclusterissuers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - cert-manager.heers.it
    resources:
      - scepclusterissuers/status
    verbs:
      - get
