# permissions for end users to edit issuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: issuer-editor-role
rules:
  - apiGroups:
      - cert-manager.heers.it
    resources:
      - issuers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cert-manager.heers.it
    resources:
      - issuers/status
    verbs:
      - get
