# permissions for end users to view issuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: issuer-viewer-role
rules:
  - apiGroups:
      - cert-manager.heers.it
    resources:
      - issuers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - cert-manager.heers.it
    resources:
      - issuers/status
    verbs:
      - get
